[package]
name = "foo"
version = "0.1.0"
edition = "2024"
publish = ["craps"]
authors = ["Luke Yoo <w.lukeyoo@gmail.com>"]
license = "BSD-3-Clause"
description = "A dummy package for registry testing"
readme = "README.md"

[dependencies]
